{...}: {
  # Using vicinae since im too lazy to write a quickshell-based launcher as of right now.
  # However I don't like it, it's daemon is too heavy. But it works for what it is, and is far
  # better than wofi.
  programs.vicinae = {
    enable = true;
    systemd.enable = true;

    themes."fht" = let
      theme = import ../../theme;

      addHashtag = attrs:
        builtins.mapAttrs (_: v:
          if builtins.typeOf v == "string"
          then {color = "#${v}";}
          else v)
        attrs;
    in {
      meta = {
        version = 1;
        name = "nferhat's Vicinae theme";
        description = "Theme generated by home-manager from nferhat's dotfiles!";
        inherits = "vicinae-dark";
        variant = "dark";
      };

      colors.core = addHashtag {
        background = theme.background.tertiary;
        foreground = theme.text.primary;
        secondary_background = theme.background.primary;
        border = theme.separator;
        accent = theme.accent;
      };

      colors.accent = addHashtag {
        blue = theme.ansi.color4;
        green = theme.ansi.color2;
        magenta = theme.ansi.color5;
        orange = theme.ansi-bright.color12;
        purple = theme.ansi-bright.color13;
        red = theme.ansi.color1;
        yellow = theme.ansi.color3;
        cyan = theme.ansi.color6;
      };
    };
  };
}
