local ok, colors = pcall(dofile,vim.fs.joinpath(os.getenv "XDG_CONFIG_HOME", "theme", "colors.lua"))
-- Try to load from configuration generated by home-manager/nix dotfiles.
-- And just in case, fallback to hardcoded values from a (not-so updated) theme.
local C
if ok then
	C = colors
else
	local Color = require("theme.color")
	C = {
		color0 = Color:new({ hex = "#161717" }),
		color1 = Color:new({ hex = "#df5b61" }),
		color2 = Color:new({ hex = "#87c7a1" }),
		color3 = Color:new({ hex = "#de8f78" }),
		color4 = Color:new({ hex = "#6791c9" }),
		color5 = Color:new({ hex = "#bc83e3" }),
		color6 = Color:new({ hex = "#70b9cc" }),
		color7 = Color:new({ hex = "#c4c4c4" }),
		color8 = Color:new({ hex = "#181819" }),
		color9 = Color:new({ hex = "#ee6a70" }),
		color10 = Color:new({ hex = "#96d6b0" }),
		color11 = Color:new({ hex = "#ffb29b" }),
		color12 = Color:new({ hex = "#7ba5dd" }),
		color13 = Color:new({ hex = "#cb92f2" }),
		color14 = Color:new({ hex = "#7fc8db" }),
		color15 = Color:new({ hex = "#cccccc" }),
		bg = {
			primary = Color:new({ hex = "#141416" }),
			secondary = Color:new({ hex = "#161618" }),
			tertiary = Color:new({ hex = "#101012" }),
		},
		text = {
			primary = Color:new({ hex = "#dedede" }),
			secondary = Color:new({ hex = "#c4c6d0" }),
			tertiary = Color:new({ hex = "#49494b" }),
		},
		separator = Color:new({ hex = "#222224" }),
	}
end

-- Best way to get "bindings" like accent->color12
-- I hate it.
return vim.tbl_extend("force", C, {
	accent = C.color12,
	error = C.color1,
	warning = C.color2,
	info = C.color4,
})
