local main = dofile(vim.fs.joinpath(os.getenv "XDG_CONFIG_HOME", "theme", "colors.lua"))
-- Additional overrides generated by matugen+dankmaterialshell
-- This is just to override background colors to make them match.
local ok, matugen_colors = pcall(dofile, vim.fs.joinpath(os.getenv "XDG_CONFIG_HOME", "theme", "colors-matugen.lua"))
if ok then
    main = vim.tbl_extend("force", main, matugen_colors)
end

return main
