local C = require("theme.colors")

local ENABLE_BG = vim.g.cmp_with_bg
local function cmp_bg(col)
	return ENABLE_BG and col or nil
end

return {
	-- base neovim tui highlights
	normal = { fg = C.foreground, bg = "none" },
	normalfloat = { fg = C.foreground },
	floatborder = { fg = C.separator },
	floattitle = C.color2,
	cold = { bold = true },
	debug = { fg = C.color1, bold = true },
	directory = C.color4,
	error = { link = "debug" },
	errormsg = { link = "debug" },
	exception = { link = "debug" },
	foldcolumn = { fg = C.color6, bg = C.color0 },
	folded = { fg = C.text.tertiary, bg = C.color0 },
	incsearch = { fg = C.color0, bg = C.color3 },
	italic = { bold = false, italic = true, underline = false },
	matchparen = { bg = C.text.tertiary, bold = true },
	modemsg = { fg = C.color6, bold = true },
	moremsg = { fg = C.color6, bold = true },
	question = { fg = C.color4, bold = true },
	search = { fg = C.color0, bg = C.color3 },
	substitute = { fg = C.color0, bg = C.color3 },
	specialkey = { fg = C.text.tertiary, italic = true },
	toolong = { fg = C.color1 },
	underlined = { bold = false, italic = false, underline = true },
	visual = { bg = C.bg.secondary },
	visualnos = { link = "visual" },
	warningmsg = { fg = C.color3, bold = true },
	wildmenu = { fg = C.color6, bg = C.bg.secondary, bold = true },
	title = C.color4,
	conceal = { fg = C.color4, bg = "none", bold = true },
	cursor = { fg = C.color3, bg = C.foreground },
	nontext = C.text.tertiary,
	linenr = { fg = C.text.tertiary:darken(5.0), bg = "none" },
	signcolumn = { fg = C.text.tertiary, bg = "none", sp = "none" }, -- match normal hl grou.
	vertsplit = { bg = "none", fg = C.separator },
	winseparator = { link = "vertsplit" },
	colorcolumn = { bg = C.color0 },
	cursorcolumn = { bg = "none" },
	cursorline = {},
	cursorlinesign = { bg = "none" },
	cursorlinenr = { fg = C.color4, bold = true },
	quickfixline = { bg = C.color0 },
	pmenu = { fg = C.color7, bg = C.bg.secondary },
	pmenusbar = { fg = C.bg.secondary, bg = C.bg.secondary },
	pmenusel = { fg = C.color4, bg = C.bg.secondary, bold = true }, -- not following base16
	pmenuthumb = { fg = C.color0, bg = C.color0 },
	tabline = { fg = C.text.tertiary, bg = C.bg.secondary },
	tablinefill = { fg = C.color8, bg = C.bg.secondary },
	tablinesel = { fg = C.color7, bg = "none", bold = true },

	-- neovim's regex syntax highlight
	boolean = C.color3,
	character = { fg = C.color1, bold = true },
	comment = C.text.tertiary,
	condition = C.color5,
	constant = C.color3,
	define = C.color5,
	delimiter = C.color1,
	float = C.color3,
	["function"] = C.color4,
	identifier = C.color7,
	include = C.color4,
	keyword = C.color5,
	label = C.color3,
	number = C.color3,
	operator = C.text.tertiary:brighten(5.0),
	preproc = C.color3,
	["repeat"] = C.color3,
	special = C.color6,
	specialchar = { link = "character" },
	statement = C.color5,
	string = C.color2,
	structure = C.color5,
	tag = C.color3,
	todo = C.color4,
	type = C.color3,
	typedef = { link = "type" },

	-- diff syntax highlighting
	diffadd = { fg = C.color2, bg = C.color0 },
	diffchange = { fg = C.color6, bg = C.color0 },
	diffdelete = { fg = C.color1, bg = C.color0 },
	difftext = { fg = C.color4, bg = C.color0 },
	diffadded = C.color2,
	difffile = C.color1,
	diffnewfile = C.color2,
	diffline = C.color4,
	diffremoved = C.color1,

	-- spell
	spellbad = { underline = true, sp = C.color1 },
	spellcap = { underline = true, sp = C.color4 },
	spellrare = { underline = true, sp = C.color5 },
	spelllocal = { underline = true, sp = C.color6 },

	-- lsp
	LspInlayHint = C.text.tertiary:darken(0.25),

	-- diagnostics
	DiagnosticError = { fg = C.color1, bold = false },
	DiagnosticWarn = { fg = C.color11:darken(3), bold = false },
	DiagnosticInfo = { fg = C.color4, bold = false },
	DiagnosticHint = { fg = C.text.tertiary, bold = false },
	DiagnosticVirtualTextError = { bg = C.bg.secondary:increase_red(4), fg = C.color1, bold = true },
	DiagnosticVirtualTextWarn = {
		bg = C.bg.secondary:increase_red(4):increase_green(4),
		fg = C.color3,
		bold = true,
	},
	DiagnosticVirtualTextInfo = { bg = C.bg.secondary:increase_blue(4), fg = C.color4, bold = true },
	DiagnosticVirtualTextHint = { bg = C.bg.secondary, fg = C.text.tertiary, bold = false },
	DiagnosticUnderlineError = { sp = C.color1, undercurl = true },
	DiagnosticUnderlineWarn = { sp = C.color3, undercurl = true },
	DiagnosticUnderlineInfo = { sp = C.color4, undercurl = true },
	DiagnosticUnderlineHint = { sp = C.text.tertiary, undercurl = false },

	-- Statusline, since its included with the config (not a plugin)
	StatusLine = { bg = C.bg.tertiary, fg = C.foreground },
	StatusLineNC = { bg = C.bg.tertiary, fg = C.foreground },
	StatusLine_mode_Normal = { fg = C.color1, bg = C.bg.tertiary },
	StatusLine_mode_Insert = { fg = C.color2, bg = C.bg.tertiary },
	Statusline_mode_Terminal = { fg = C.color1, bg = C.bg.tertiary },
	Statusline_mode_Visual = { fg = C.color4, bg = C.bg.tertiary },
	Statusline_mode_Select = { fg = C.color3, bg = C.bg.tertiary },
	Statusline_mode_Command = { fg = C.color5, bg = C.bg.tertiary },
	Statusline_mode_Confirm = { fg = C.color6, bg = C.bg.tertiary },
	Statusline_mode_NTerminal = { link = "Statusline_mode_term", bold = true },
	-- Filetype section
	Statusline_filetype_default = { bg = C.bg.tertiary, fg = C.color1 },
	Statusline_filetype_name = { bg = C.bg.tertiary, fg = C.foreground },
	-- Filename section
	Statusline_filename_normal = { bg = C.bg.tertiary, fg = C.foreground },
	Statusline_filename_modified = { bg = C.bg.tertiary, fg = C.color4 },
	Statusline_filename_readonly = { bg = C.bg.tertiary, fg = C.color1 },
	-- LSP clients section
	Statusline_lspclients = { bg = C.bg.tertiary, fg = C.color6, italic = true },
	-- current macro section
	Statusline_macro = { bg = C.bg.tertiary, fg = C.color3, bold = true },
	-- Separator
	Statusline_separator = { bg = C.bg.tertiary, fg = C.separator },
	-- Git section
	Statusline_git_branch_icon = { bg = C.bg.tertiary, fg = C.color5 },
	Statusline_git_diff_added = { bg = C.bg.tertiary, fg = C.color2 },
	Statusline_git_diff_changed = { bg = C.bg.tertiary, fg = C.color4 },
	Statusline_git_diff_removed = { bg = C.bg.tertiary, fg = C.color1 },
	-- Diagnostics section
	Statusline_diagnostic_error = { fg = C.color1, bold = true, bg = C.bg.tertiary },
	Statusline_diagnostic_warn = { fg = C.color3, bold = true, bg = C.bg.tertiary },
	Statusline_diagnostic_info = { fg = C.color4, bold = true, bg = C.bg.tertiary },
	Statusline_diagnostic_hint = { fg = C.text.tertiary, bold = false, bg = C.bg.tertiary },
	-- Other filler
	Statusline_misc_text = { bg = C.bg.tertiary, fg = C.text.tertiary, italic = false },
	Statusline_text = { bg = C.bg.tertiary, fg = C.foreground },
	-- Line and column
	Statusline_linecol = { bg = C.bg.tertiary, fg = C.foreground },

	-- renamer, see lua/renamer
	RenamerTitle = { bg = C.color2, fg = C.color0 },

	-- tree-sitter is now included with neovim, aswell as some parsers
	-- make the highlights for syntax nodes in the base skeleton
	["@boolean"] = C.color3,
	["@character"] = { fg = C.color1, bold = true },
	["@character.special"] = C.color6,
	["@comment"] = C.text.tertiary:brighten(1.0),
	["@conditional"] = C.color5,
	["@constant"] = { fg = C.color3, italic = false },
	["@constant.builtin"] = C.color11,
	["@constant.macro"] = C.color7,
	["@constructor"] = C.color3,
	["@constructor.lua"] = C.text.tertiary:brighten(1.0), -- lua brackets for objects
	["@debug"] = C.color1,
	["@define"] = C.color5,
	["@exception"] = { link = "Exception" },
	["@field"] = C.foreground,
	["@float"] = { link = "Float" },
	["@function"] = C.color4,
	["@function.builtin"] = C.color4,
	["@function.macro"] = C.color7,
	["@include"] = { link = "Include" },
	["@keyword"] = { fg = C.color5, italic = false },
	["@label"] = C.color3,
	["@macro"] = C.color7,
	["@module"] = C.text.tertiary:brighten(5.0),
	["@method"] = { link = "@function" },
	["@namespace"] = C.text.tertiary:brighten(5.0),
	["@number"] = C.color3,
	["@operator"] = C.text.tertiary:brighten(5.0),
	["@parameter"] = { fg = C.foreground, italic = true },
	["@preproc"] = C.color3,
	["@property"] = C.foreground,
	["@punctuation"] = C.text.tertiary:brighten(5.0),
	["@punctuation.special"] = C.text.tertiary:brighten(5.0),
	["@punctuation.special.markdown"] = C.separator,
	["@repeat"] = { fg = C.color3, italic = false },
	["@storageclass"] = { fg = C.color3, italic = true },
	["@string"] = C.color2,
	["@string.escape"] = C.color4,
	["@string.special"] = { fg = C.color6, bold = true },
	["@tag"] = C.color3,
	["@text.title"] = C.color6,
	["@text.todo"] = C.color4,
	["@text.reference"] = C.color5,
	["@text.uri"] = C.color4,
	["@type"] = { fg = C.color11, italic = false },
	["@type.builtin"] = { fg = C.color3, italic = false },
	["@type.definition"] = { link = "@type" },
	["@variable"] = C.foreground,
	["@variable.builtin"] = C.foreground,
	["@variable.builtin.rust"] = C.foreground,
	-- Markdown
	["@markup.raw"] = C.color7,
	["@markup.raw.markdown_inline"] = { bg = C.bg.secondary:brighten(5), fg = C.color7 },
	["@markup.link.label"] = C.color4,
	["@markup.link.url"] = C.color9,
	-- wgsl
	["@attribute.wgsl"] = C.color7:darken(5.0),
	-- Rust
	["@keyword.modifier.rust"] = { fg = C.color3, italic = false },
	["@variable.builtin.rust"] = { link = "@variable" },

	-- lazy.nvim
	LazyButton = { bg = C.bg.secondary },

	-- gitsigns.nvim
	GitSignsAdd = C.color2,
	GitSignsChange = C.color4,
	GitSignsChangeDelete = C.color1,
	GitSignsDelete = C.color1,
	GitSignsTopDelete = C.color9,
	GitSignsUntracked = C.text.tertiary,

	-- snacks.nvim
	SnacksPickerBoxTitle = { bg = C.color2, fg = C.bg.primary },
	SnacksPickerInput = { link = "NormalFloat" },
	SnacksPickerInputBorder = { link = "FloatBorder" },
	SnacksPickerList = { link = "NormalFloat" },
	SnacksPickerListBorder = { link = "FloatBorder" },
	SnacksPickerListCursorLine = { bg = C.bg.secondary, bold = true },
	SnacksPickerPreview = { link = "NormalFloat" },
	SnacksPickerPreviewBorder = { link = "FloatBorder" },
	SnacksIndent = C.separator:brighten(1.5),
	SnacksIndentScope = C.separator:brighten(10.0),
	-- Input, for prompts generally
	SnacksInputNormal = { bg = C.bg.secondary },
	SnacksInputBorder = { bg = C.bg.secondary, fg = C.bg.secondary },
	SnacksInputTitle = { bg = C.color5, fg = C.bg.secondary, bold = true },

	-- noice.nvim
	-- Base highlights that we are linking against, I don't like the colors
	-- to change based on *what* I am going todo in the command line
	NoiceCmdlinePopup = { link = "NormalFloat" },
	NoiceCmdlinePopupBorder = { link = "FloatBorder" },
	NoiceCmdlinePopupTitle = C.text.tertiary,
	-- Now link these to match with the base highlight
	NoiceCmdlinePopupBorderCalculator = { link = "FloatBorder" },
	NoiceCmdlinePopupBorderCmdline = { link = "FloatBorder" },
	NoiceCmdlinePopupBorderFilter = { link = "FloatBorder" },
	NoiceCmdlinePopupBorderSearch = { link = "FloatBorder" },
	NoiceCmdlinePopupBorderInput = { link = "FloatBorder" },
	NoiceCmdlinePopupBorderLua = { link = "FloatBorder" },
	-- The popup menu that does completions to the cmdline
	NoicePopupmenu = { link = "NormalFloat" },
	NoicePopupmenuBorder = { link = "FloatBorder" },
	NoicePopupmenuSelected = { bg = C.bg.secondary, bold = true },
	NoicePopupmenuMatch = { fg = C.color4, bold = true },
	NoiceScrollbar = { bg = "none", fg = "none" },
	NoiceScrollbarThumb = { bg = C.bg.secondary:darken(2.0), fg = C.color5 },
	-- Split view
	NoiceSplit = { bg = C.bg.secondary:darken(2.0) },
	NoiceSplitBorder = { bg = C.bg.secondary:darken(2.0) },

	-- blink.cmp
	BlinkCmpMenu = { link = "normalfloat" },
	BlinkCmpDoc = { link = "normalfloat" },
	BlinkCmpDocBorder = { link = "floatborder" },
	BlinkCmpMenuBorder = { link = "floatborder" },
	BlinkCmpLabelDetail = { fg = C.text.tertiary:darken(5) },
	BlinkCmpLabel = C.foreground,
	BlinkCmpScrollBarThumb = { bg = C.separator },
	BlinkCmpScrollBarGutter = { link = "BlinkCmpMenu" },
	BlinkCmpMenuSelection = { bg = C.bg.secondary:darken(2) },
	BlinkCmpLabelDeprecated = { strikethrough = true },
	BlinkCmpLabelMatch = { bold = true },
	-- Client item kinds, the following are builtin to cmp.
	CmpItemAbbrDeprecated = { fg = C.color7, strikethrough = true },
	CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
	CmpItemAbbrMatch = { fg = C.color4, bold = true },
	BlinkCmpKindSnippet = { fg = C.color2, bg = cmp_bg(C.bg.tertiary:increase_green(4)) },
	BlinkCmpKindConstant = {
		fg = C.color3,
		bg = cmp_bg(C.bg.tertiary:increase_red(4):increase_green(2):brighten(1)),
	},
	BlinkCmpKindConstructor = C.color4,
	BlinkCmpKindEnum = { link = "BlinkCmpKindConstant" },
	BlinkCmpKindEnumMember = { link = "BlinkCmpKindConstant" },
	BlinkCmpKindEvent = { fg = C.color1, bg = cmp_bg(C.bg.tertiary:increase_red(4)) },
	BlinkCmpKindInterface = { link = "BlinkCmpKindConstant" },
	BlinkCmpKindKeyword = { fg = C.color5, bg = cmp_bg(C.bg.tertiary:increase_red(6):increase_blue(6)) },
	BlinkCmpKindClass = { link = "BlinkCmpKindConstant" },
	BlinkCmpKindModule = { link = "BlinkCmpKindEvent" },
	BlinkCmpKindOperator = C.text.tertiary,
	BlinkCmpKindTypeParameter = { link = "BlinkCmpKindConstant" },
	BlinkCmpKindUnit = { link = "BlinkCmpKindSnippet" },
	BlinkCmpKindField = {
		fg = C.color6,
		bg = cmp_bg(C.bg.tertiary:increase_green(4):increase_blue(4):brighten(4)),
	},
	BlinkCmpKindVariable = { link = "BlinkCmpKindField" },
	BlinkCmpKindText = { fg = C.text.tertiary, bg = cmp_bg(C.bg.secondary:darken(1)) },
	BlinkCmpKindFunction = { fg = C.color4, bg = cmp_bg(C.bg.tertiary:increase_blue(2):brighten(4)) },
	BlinkCmpKindMethod = { link = "BlinkCmpKindFunction" },
	BlinkCmpKindProperty = { link = "BlinkCmpKindKeyword" },
	BlinkCmpKindFolder = { fg = "#f1d068" },
	BlinkCmpKindFile = { link = "BlinkCmpKindEvent" },
	BlinkCmpKindStruct = { link = "BlinkCmpKindConstant" },

	-- mini.clue
	MiniClueDescSingle = { fg = C.color7 },
	MiniClueDescGroup = { fg = C.color7, bold = true },
	MiniClueNextKey = { fg = C.color4 },
	MiniClueNextKeyWithPostkeys = { link = "MiniClueNextKey" },
	MiniClueSeparator = { fg = C.separator },
	MiniClueTitle = { fg = C.color4, bold = true },
	MiniClueBorder = { link = "FloatBorder" },
}
