local C = require "theme.colors"

local ENABLE_BG = vim.g.cmp_with_bg
local function cmp_bg(col)
    return ENABLE_BG and col or nil
end

return {
    -- base neovim tui highlights
    normal = { fg = C.foreground, bg = "none" },
    normalfloat = { fg = C.foreground, bg = C.light_background },
    floatborder = { bg = C.light_background },
    floattitle = { bg = C.color2, fg = C.background },
    cold = { bold = true },
    debug = { fg = C.color1, bold = true },
    directory = C.color4,
    error = { link = "debug" },
    errormsg = { link = "debug" },
    exception = { link = "debug" },
    foldcolumn = { fg = C.color6, bg = C.color0 },
    folded = { fg = C.comment, bg = C.color0 },
    incsearch = { fg = C.color0, bg = C.color3 },
    italic = { bold = false, italic = true, underline = false },
    matchparen = { bg = C.comment, bold = true },
    modemsg = { fg = C.color6, bold = true },
    moremsg = { fg = C.color6, bold = true },
    question = { fg = C.color4, bold = true },
    search = { fg = C.color0, bg = C.color3 },
    substitute = { fg = C.color0, bg = C.color3 },
    specialkey = { fg = C.comment, italic = true },
    toolong = { fg = C.color1 },
    underlined = { bold = false, italic = false, underline = true },
    visual = { bg = C.selection },
    visualnos = { link = "visual" },
    warningmsg = { fg = C.color3, bold = true },
    wildmenu = { fg = C.color6, bg = C.selection, bold = true },
    title = C.color4,
    conceal = { fg = C.color4, bg = "none", bold = true },
    cursor = { fg = C.color3, bg = C.foreground },
    nontext = C.comment,
    linenr = { fg = C.comment:darken(5.0), bg = "none" },
    signcolumn = { fg = C.comment, bg = "none", sp = "none" }, -- match normal hl grou.
    vertsplit = { bg = "none", fg = C.border },
    winseparator = { link = "vertsplit" },
    colorcolumn = { bg = C.color0 },
    cursorcolumn = { bg = "none" },
    cursorline = {},
    cursorlinesign = { bg = "none" },
    cursorlinenr = { fg = C.color4, bold = true },
    quickfixline = { bg = C.color0 },
    pmenu = { fg = C.color7, bg = C.light_background },
    pmenusbar = { fg = C.light_background, bg = C.light_background },
    pmenusel = { fg = C.color4, bg = C.selection, bold = true }, -- not following base16
    pmenuthumb = { fg = C.color0, bg = C.color0 },
    tabline = { fg = C.comment, bg = C.light_background },
    tablinefill = { fg = C.color8, bg = C.light_background },
    tablinesel = { fg = C.color7, bg = "none", bold = true },

    -- neovim's regex syntax highlight
    boolean = C.color3,
    character = { fg = C.color1, bold = true },
    comment = C.comment,
    condition = C.color5,
    constant = C.color3,
    define = C.color5,
    delimiter = C.color1,
    float = C.color3,
    ["function"] = C.color4,
    identifier = C.color1,
    include = C.color4,
    keyword = C.color5,
    label = C.color3,
    number = C.color3,
    operator = C.color7,
    preproc = C.color3,
    ["repeat"] = C.color3,
    special = C.color6,
    specialchar = { link = "character" },
    statement = C.color5,
    string = C.color2,
    structure = C.color5,
    tag = C.color3,
    todo = C.color4,
    type = { fg = C.color3, bold = true },
    typedef = { link = "type" },

    -- diff syntax highlighting
    diffadd = { fg = C.color2, bg = C.color0 },
    diffchange = { fg = C.color6, bg = C.color0 },
    diffdelete = { fg = C.color1, bg = C.color0 },
    difftext = { fg = C.color4, bg = C.color0 },
    diffadded = C.color2,
    difffile = C.color1,
    diffnewfile = C.color2,
    diffline = C.color4,
    diffremoved = C.color1,

    -- spell
    spellbad = { underline = true, sp = C.color1 },
    spellcap = { underline = true, sp = C.color4 },
    spellrare = { underline = true, sp = C.color5 },
    spelllocal = { underline = true, sp = C.color6 },

    -- lsp
    LspInlayHint = C.comment:darken(0.25),

    -- diagnostics
    DiagnosticError = { fg = C.color1, bold = false },
    DiagnosticWarn = { fg = C.color11:darken(3), bold = false },
    DiagnosticInfo = { fg = C.color4, bold = false },
    DiagnosticHint = { fg = C.comment, bold = false },
    DiagnosticVirtualTextError = { bg = C.light_background:increase_red(4), fg = C.color1, bold = true },
    DiagnosticVirtualTextWarn = {
        bg = C.light_background:increase_red(4):increase_green(4),
        fg = C.color3,
        bold = true,
    },
    DiagnosticVirtualTextInfo = { bg = C.light_background:increase_blue(4), fg = C.color4, bold = true },
    DiagnosticVirtualTextHint = { bg = C.light_background, fg = C.comment, bold = false },
    DiagnosticUnderlineError = { sp = C.color1, undercurl = true },
    DiagnosticUnderlineWarn = { sp = C.color3, undercurl = true },
    DiagnosticUnderlineInfo = { sp = C.color4, undercurl = true },
    DiagnosticUnderlineHint = { sp = C.comment, undercurl = false },

    -- Statusline, since its included with the config (not a plugin)
    StatusLine = { bg = C.dark_background, fg = C.foreground },
    StatusLineNC = { bg = C.dark_background, fg = C.foreground },
    StatusLine_mode_Normal = { fg = C.color1, bg = C.dark_background },
    StatusLine_mode_Insert = { fg = C.color2, bg = C.dark_background },
    Statusline_mode_Terminal = { fg = C.color1, bg = C.dark_background },
    Statusline_mode_Visual = { fg = C.color4, bg = C.dark_background },
    Statusline_mode_Select = { fg = C.color3, bg = C.dark_background },
    Statusline_mode_Command = { fg = C.color5, bg = C.dark_background },
    Statusline_mode_Confirm = { fg = C.color6, bg = C.dark_background },
    Statusline_mode_NTerminal = { link = "Statusline_mode_term", bold = true },
    -- Filetype section
    Statusline_filetype_default = { bg = C.dark_background, fg = C.color1 },
    Statusline_filetype_name = { bg = C.dark_background, fg = C.foreground },
    -- Filename section
    Statusline_filename_normal = { bg = C.dark_background, fg = C.foreground },
    Statusline_filename_modified = { bg = C.dark_background, fg = C.color4 },
    Statusline_filename_readonly = { bg = C.dark_background, fg = C.color1 },
    -- LSP clients section
    Statusline_lspclients = { bg = C.dark_background, fg = C.color6, italic = true },
    -- current macro section
    Statusline_macro = { bg = C.dark_background, fg = C.color3, bold = true },
    -- Separator
    Statusline_separator = { bg = C.dark_background, fg = C.border },
    -- Git section
    Statusline_git_branch_icon = { bg = C.dark_background, fg = C.color5 },
    Statusline_git_diff_added = { bg = C.dark_background, fg = C.color2 },
    Statusline_git_diff_changed = { bg = C.dark_background, fg = C.color4 },
    Statusline_git_diff_removed = { bg = C.dark_background, fg = C.color1 },
    -- Diagnostics section
    Statusline_diagnostic_error = { fg = C.color1, bold = true, bg = C.dark_background },
    Statusline_diagnostic_warn = { fg = C.color3, bold = true, bg = C.dark_background },
    Statusline_diagnostic_info = { fg = C.color4, bold = true, bg = C.dark_background },
    Statusline_diagnostic_hint = { fg = C.comment, bold = false, bg = C.dark_background },
    -- Other filler
    Statusline_misc_text = { bg = C.dark_background, fg = C.comment, italic = false },
    Statusline_text = { bg = C.dark_background, fg = C.foreground },
    -- Line and column
    Statusline_linecol = { bg = C.dark_background, fg = C.foreground },

    -- renamer, see lua/renamer
    RenamerTitle = { bg = C.color2, fg = C.color0 },

    -- tree-sitter is now included with neovim, aswell as some parsers
    -- make the highlights for syntax nodes in the base skeleton
    ["@boolean"] = C.color3,
    ["@character"] = { fg = C.color1, bold = true },
    ["@character.special"] = C.color6,
    ["@comment"] = C.comment:brighten(1.0),
    ["@conditional"] = C.color5,
    ["@constant"] = { fg = C.color3, italic = false },
    ["@constant.builtin"] = C.color3,
    ["@constant.macro"] = C.color7,
    ["@constructor"] = C.color3,
    ["@debug"] = C.color1,
    ["@define"] = C.color5,
    ["@exception"] = { link = "Exception" },
    ["@field"] = C.foreground,
    ["@float"] = { link = "Float" },
    ["@function"] = C.color4,
    ["@function.builtin"] = C.color4,
    ["@function.macro"] = C.color7,
    ["@include"] = { link = "Include" },
    ["@keyword"] = { fg = C.color5, italic = false },
    -- Special case for rust &mut
    ["@keyword.modifier.rust"] = { fg = C.color3, italic = false },
    ["@label"] = C.color3,
    ["@macro"] = C.color7,
    ["@module"] = C.comment:brighten(5.0),
    ["@method"] = { link = "@function" },
    ["@namespace"] = C.color1,
    ["@number"] = C.color3,
    ["@operator"] = C.color7:darken(2.5),
    ["@parameter"] = { fg = C.foreground, italic = true },
    ["@preproc"] = C.color3,
    ["@property"] = C.foreground,
    ["@punctuation"] = C.comment:brighten(5.0),
    ["@punctuation.special"] = C.comment:brighten(5.0),
    ["@repeat"] = { fg = C.color3, italic = false },
    ["@storageclass"] = { fg = C.color3, italic = true },
    ["@string"] = C.color2,
    ["@string.escape"] = C.color4,
    ["@string.special"] = { fg = C.color6, bold = true },
    ["@tag"] = C.color3,
    ["@text.title"] = C.color6,
    ["@text.todo"] = C.color4,
    ["@text.reference"] = C.color5,
    ["@text.uri"] = C.color4,
    ["@type"] = { fg = C.color11, italic = false },
    ["@type.builtin"] = { fg = C.color3, italic = false },
    ["@type.definition"] = { link = "@type" },
    ["@variable"] = C.foreground,
    ["@variable.builtin"] = C.foreground,
    -- Markdown
    ["@markup.raw"] = C.color7,
    ["@markup.link.label"] = C.color4,
    ["@markup.link.url"] = C.color9,

    -- lazy.nvim
    LazyButton = { bg = C.light_background },

    -- gitsigns.nvim
    GitSignsAdd = C.color2,
    GitSignsChange = C.color4,
    GitSignsChangeDelete = C.color1,
    GitSignsDelete = C.color1,
    GitSignsTopDelete = C.color9,
    GitSignsUntracked = C.comment,

    -- snacks.nvim
    SnacksPickerBoxTitle = { bg = C.color2, fg = C.background },
    SnacksPickerInput = { bg = C.light_background },
    SnacksPickerInputBorder = { bg = C.light_background, fg = C.border },
    SnacksPickerList = { bg = C.light_background },
    SnacksPickerListBorder = { bg = C.light_background, fg = C.border },
    SnacksPickerListCursorLine = { bg = C.light_background, bold = true },
    SnacksPickerPreview = { bg = C.light_background:darken(2.0) },
    SnacksPickerPreviewBorder = { bg = C.light_background:darken(2.0) },
    SnacksIndent = C.border:brighten(1.5),
    SnacksIndentScope = C.border:brighten(10.0),
    -- Input, for prompts generally
    SnacksInputNormal = { bg = C.light_background },
    SnacksInputBorder = { bg = C.light_background, fg = C.light_background },
    SnacksInputTitle = { bg = C.color5, fg = C.light_background, bold = true },

    -- noice.nvim
    -- Base highlights that we are linking against, I don't like the colors
    -- to change based on *what* I am going todo in the command line
    NoiceCmdlinePopup = { link = "NormalFloat" },
    NoiceCmdlinePopupBorder = { link = "FloatBorder" },
    NoiceCmdlinePopupTitle = { bg = C.color2, fg = C.background },
    -- Now link these to match with the base highlight
    NoiceCmdlinePopupBorderCalculator = { link = "FloatBorder" },
    NoiceCmdlinePopupBorderCmdline = { link = "FloatBorder" },
    NoiceCmdlinePopupBorderFilter = { link = "FloatBorder" },
    NoiceCmdlinePopupBorderSearch = { link = "FloatBorder" },
    NoiceCmdlinePopupBorderInput = { link = "FloatBorder" },
    NoiceCmdlinePopupBorderLua = { link = "FloatBorder" },
    -- And since noice links these to the border color, which is not what I want
    NoiceCmdlinePopupTitleCmdline = { bg = C.color2, fg = C.background, bold = true },
    NoiceCmdlinePopupTitleFilter = { bg = C.color3, fg = C.background, bold = true },
    NoiceCmdlinePopupTitleSearch = { bg = C.color3, fg = C.background, bold = true },
    NoiceCmdlinePopupTitleInput = { bg = C.color5, fg = C.background, bold = true },
    NoiceCmdlinePopupTitleLua = { bg = C.color6, fg = C.background, bold = true },
    -- The popup menu that does completions to the cmdline
    NoicePopupmenu = { bg = C.light_background:darken(2.0) },
    NoicePopupmenuBorder = { bg = C.light_background:darken(2.0) },
    NoicePopupmenuSelected = { bg = C.light_background },
    NoicePopupmenuMatch = { fg = C.color4, bold = true },
    NoiceScrollbar = { bg = "none", fg = C.color5 },
    NoiceScrollbarThumb = { bg = C.light_background:darken(2.0), fg = C.color5 },
    -- Split view
    NoiceSplit = { bg = C.light_background:darken(2.0) },
    NoiceSplitBorder = { bg = C.light_background:darken(2.0) },

    -- notify.nvim
    NotifyDebugBorder = { link = "FloatBorder" },
    NotifyErrorBorder = { link = "FloatBorder" },
    NotifyInfoBorder = { link = "FloatBorder" },
    NotifyTraceBorder = { link = "FloatBorder" },
    NotifyWarnBorder = { link = "FloatBorder" },
    NotifyDebugBody = { link = "NormalFloat" },
    NotifyErrorBody = { link = "NormalFloat" },
    NotifyInfoBody = { link = "NormalFloat" },
    NotifyTraceBody = { link = "NormalFloat" },
    NotifyWarnBody = { link = "NormalFloat" },
    NotifyDebugBody2 = { link = "NormalFloat" },
    NotifyErrorBody2 = { link = "NormalFloat" },
    NotifyInfoBody2 = { link = "NormalFloat" },
    NotifyTraceBody2 = { link = "NormalFloat" },
    NotifyWarnBody2 = { link = "NormalFloat" },
    NotifySeparator = C.border,
    NotifyDebugIcon = { fg = C.color9, bg = C.light_background },
    NotifyErrorIcon = { fg = C.color1, bg = C.light_background },
    NotifyInfoIcon = { fg = C.color4, bg = C.light_background },
    NotifyTraceIcon = { fg = C.color5, bg = C.light_background },
    NotifyWarnIcon = { fg = C.color3, bg = C.light_background },
    NotifyDebugTitle = { fg = C.color9, bg = C.light_background },
    NotifyErrorTitle = { fg = C.color1, bg = C.light_background },
    NotifyInfoTitle = { fg = C.color4, bg = C.light_background },
    NotifyTraceTitle = { fg = C.color5, bg = C.light_background },
    NotifyWarnTitle = { fg = C.color3, bg = C.light_background },

    -- blink.cmp
    BlinkCmpMenu = { bg = C.light_background },
    BlinkCmpDoc = { bg = C.light_background:darken(2.0) },
    BlinkCmpDocBorder = { bg = C.light_background:darken(2.0) },
    BlinkCmpMenuBorder = { link = "BlinkCmpMenu" },
    BlinkCmpLabelDetail = { bg = C.light_background, fg = C.comment:darken(5) },
    BlinkCmpLabel = C.foreground,
    BlinkCmpScrollBarThumb = { bg = C.border },
    BlinkCmpScrollBarGutter = { link = "BlinkCmpMenu" },
    BlinkCmpMenuSelection = { bg = C.light_background:darken(2) },
    BlinkCmpLabelDeprecated = { strikethrough = true },
    BlinkCmpLabelMatch = { bold = true },
    -- Client item kinds, the following are builtin to cmp.
    CmpItemAbbrDeprecated = { fg = C.color7, strikethrough = true },
    CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
    CmpItemAbbrMatch = { fg = C.color4, bold = true },
    BlinkCmpKindSnippet = { fg = C.color2, bg = cmp_bg(C.dark_background:increase_green(4)) },
    BlinkCmpKindConstant = {
        fg = C.color3,
        bg = cmp_bg(C.dark_background:increase_red(4):increase_green(2):brighten(1)),
    },
    BlinkCmpKindConstructor = C.color4,
    BlinkCmpKindEnum = { link = "BlinkCmpKindConstant" },
    BlinkCmpKindEnumMember = { link = "BlinkCmpKindConstant" },
    BlinkCmpKindEvent = { fg = C.color1, bg = cmp_bg(C.dark_background:increase_red(4)) },
    BlinkCmpKindInterface = { link = "BlinkCmpKindConstant" },
    BlinkCmpKindKeyword = { fg = C.color5, bg = cmp_bg(C.dark_background:increase_red(6):increase_blue(6)) },
    BlinkCmpKindClass = { link = "BlinkCmpKindConstant" },
    BlinkCmpKindModule = { link = "BlinkCmpKindEvent" },
    BlinkCmpKindOperator = C.comment,
    BlinkCmpKindTypeParameter = { link = "BlinkCmpKindConstant" },
    BlinkCmpKindUnit = { link = "BlinkCmpKindSnippet" },
    BlinkCmpKindField = { fg = C.color6, bg = cmp_bg(C.dark_background:increase_green(4):increase_blue(4):brighten(4)) },
    BlinkCmpKindVariable = { link = "BlinkCmpKindField" },
    BlinkCmpKindText = { fg = C.comment, bg = cmp_bg(C.light_background:darken(1)) },
    BlinkCmpKindFunction = { fg = C.color4, bg = cmp_bg(C.dark_background:increase_blue(2):brighten(4)) },
    BlinkCmpKindMethod = { link = "BlinkCmpKindFunction" },
    BlinkCmpKindProperty = { link = "BlinkCmpKindKeyword" },
    BlinkCmpKindFolder = { fg = "#f1d068" },
    BlinkCmpKindFile = { link = "BlinkCmpKindEvent" },
    BlinkCmpKindStruct = { link = "BlinkCmpKindConstant" },

    -- mini.clue
    MiniClueDescSingle = { bg = C.light_background:darken(2.0), fg = C.color4 },
    MiniClueDescGroup = { bg = C.light_background:darken(2.0), fg = C.color12, bold = true },
    MiniClueNextKey = { bg = C.light_background:darken(2.0), fg = C.color5 },
    MiniClueNextKeyWithPostkeys = { link = "MiniClueNextKey" },
    MiniClueSeparator = { bg = C.light_background:darken(2.0), fg = C.border },
    MiniClueTitle = { bg = C.light_background:darken(2.0), fg = C.color4, bold = true },
    MiniClueBorder = { bg = C.light_background:darken(2.0) },

    -- flutter-tools
    FlutterWidgetGuides = { fg = C.comment:darken(7) },

    -- render-markdown.nvim
    RenderMarkdownCode = { bg = C.dark_background },
    RenderMarkdownTableHead = { fg = C.border:lighten(2.0) },
    RenderMarkdownTableRow = { fg = C.border:lighten(2.0) },
    RenderMarkdownWarn = { fg = C.color3 },
    RenderMarkdownInfo = { fg = C.color4 },
    RenderMarkdownSuccess = { fg = C.color2 },
    RenderMarkdownCodeInline = { fg = C.color7, bg = C.color8 },
    -- These are part of treesitter highlights but are also picked up by the plugin
    ["@markup.quote.markdown"] = { fg = C.color16 },
    ["@markup.heading.1.markdown"] = { fg = C.color4 },
    ["@markup.heading.2.markdown"] = { fg = C.color2 },
    ["@markup.heading.3.markdown"] = { fg = C.color6 },
    ["@markup.heading.4.markdown"] = { fg = C.color1 },
    ["@markup.heading.5.markdown"] = { fg = C.color5 },
    ["@markup.heading.6.markdown"] = { fg = C.color5 },
    RenderMarkdownH1Bg = { bg = C.light_background:increase_blue(2.0) },
    RenderMarkdownH2Bg = { bg = C.light_background:increase_green(2.0) },
    RenderMarkdownH3Bg = { bg = C.light_background:increase_blue(2.0):increase_green(2.0) },
    RenderMarkdownH4Bg = { bg = C.light_background:increase_red(2.0), },
    RenderMarkdownH5Bg = { bg = C.light_background:increase_red(6.0):increase_blue(6.0) },
    RenderMarkdownH6Bg = { bg = C.light_background:increase_red(3.0):increase_blue(3.0) },
}
