-- DO NOT TOUCH. This is generated by matugen
local Color = require "theme.color"
return {
    dark_background = Color:new { hex = "{{ colors.surface_container_low.default.hex }}" },
    background = Color:new { hex = "{{ colors.surface.default.hex }}" },
    light_background = Color:new { hex = "{{ colors.surface_container.default.hex }}" },
    comment = Color:new { hex = "{{ colors.outline_variant.default.hex }}" },
    border = (Color:new { hex = "{{ colors.outline_variant.default.hex }}" }):darken(5.0),
    hint = (Color:new { hex = "{{ colors.outline_variant.default.hex }}" }):brighten(3.5),
    foreground = Color:new { hex = "{{ colors.on_surface.default.hex }}" },
    color7 = Color:new { hex = "{{ colors.on_surface.default.hex }}" },
    color15 = Color:new { hex = "{{ colors.on_surface.default.hex }}" },
}
