{
  inputs',
  pkgs,
  ...
}: {
  # NOTE: Don't use `programs.neovim` since I manage my configuration myself.

  home = {
    packages = with pkgs; [
      # Use latest neovim for `vim.pack` manager
      inputs'.neovim-nightly.packages.default
      ripgrep
      fd
      # For language servers, flake.nix and shell.nix in projects install them.
      # If needed I can just start them manually.
    ];

    sessionVariables = {
      EDITOR = "nvim";
      VISUAL = "nvim";
    };
  };

  xdg.configFile = {
    "nvim" = {
      enable = true;
      source = ../../config/nvim;
      # We have to make it recursive to be able to install parsers in nvim/parsers,
      # if this option is set to false, we will try to symlink into the nix store.
      recursive = true;
    };

    # FIXME: Actually use the correct names, I didn't change it from my ooold neovim config
    "theme/colors.lua".text = let
      theme = import ../../theme;
    in ''
      -- DO NOT TOUCH. This is generated by theme-manager
      local Color = require "theme.color"
      return {
          dark_background = Color:new { hex = "#${theme.background.tertiary}" },
          background = Color:new { hex = "#${theme.background.primary}" },
          light_background = Color:new { hex = "#${theme.background.secondary}" },
          selection = Color:new { hex = "#${theme.background.secondary}" },
          hint = Color:new({ hex = "#${theme.text.tertiary}" }):brighten(3.5),
          border = Color:new { hex = "#${theme.separator}" },
          comment = Color:new { hex = "#${theme.text.tertiary}" },
          foreground = Color:new { hex = "#${theme.text.primary}" },
          color0 = Color:new { hex = "#${theme.ansi.color0}" },
          color1 = Color:new { hex = "#${theme.ansi.color1}" },
          color2 = Color:new { hex = "#${theme.ansi.color2}" },
          color3 = Color:new { hex = "#${theme.ansi.color3}" },
          color4 = Color:new { hex = "#${theme.ansi.color4}" },
          color5 = Color:new { hex = "#${theme.ansi.color5}" },
          color6 = Color:new { hex = "#${theme.ansi.color6}" },
          color7 = Color:new { hex = "#${theme.ansi.color7}" },
          color8 = Color:new { hex = "#${theme.ansi-bright.color8}" },
          color9 = Color:new { hex = "#${theme.ansi-bright.color9}" },
          color10 = Color:new { hex = "#${theme.ansi-bright.color10}" },
          color11 = Color:new { hex = "#${theme.ansi-bright.color11}" },
          color12 = Color:new { hex = "#${theme.ansi-bright.color12}" },
          color13 = Color:new { hex = "#${theme.ansi-bright.color13}" },
          color14 = Color:new { hex = "#${theme.ansi-bright.color14}" },
          color15 = Color:new { hex = "#${theme.ansi-bright.color15}" },
      }
    '';
  };
}
