local C = require "ui.theme.colors"

return {
    -- base neovim tui highlights
    Normal = { fg = C.on_background, bg = C.surface },
    NormalFloat = { fg = C.on_background, bg = "none" },
    Floatborder = { bg = "none", fg = C.color17 },
    Bold = { bold = true },
    Debug = { fg = C.color1, bold = true },
    Directory = C.color4,
    Error = { link = "debug" },
    ErrorMsg = { link = "debug" },
    Exception = { link = "debug" },
    FoldColumn = { fg = C.color6, bg = C.surface },
    Folded = { fg = C.on_surface_low, bg = C.surface_bright, italic = true },
    IncSearch = { fg = C.surface_container_low, bg = C.color3, bold = true },
    Italic = { italic = true },
    MatchParen = { bg = C.surface_container, bold = true },
    ModeMsg = { fg = C.color6, bold = true },
    MoreMsg = { fg = C.color6, bold = true },
    Question = { fg = C.color4, bold = true },
    Search = { link = "IncSearch" },
    Substitute = { link = "IncSearch" },
    SpecialKey = { fg = C.on_surface_low, italic = true },
    TooLong = { fg = C.color1 },
    Underlined = { underline = true },
    Visual = { bg = C.surface_container },
    VisualNOS = { link = "visual" },
    WarningMsg = { fg = C.color3, bold = true },
    Title = C.color4,
    Conceal = { fg = C.color4, bg = "none", bold = true },
    Cursor = { fg = C.color3, bg = C.on_background },
    NonText = C.color16,
    LineNr = { fg = C.color17, bg = "none" },
    Signcolumn = { fg = C.color16, bg = "none", sp = "none" }, -- match normal hl grou.
    Statusline = { bg = C.surface_container, fg = C.color7 },
    StatuslineNC = { bg = C.surface_container, fg = C.surface_container },
    VertSplit = { bg = "none", fg = C.color17 },
    ColorColumn = { bg = C.color0 },
    CursorColumn = { bg = "none" },
    Cursorline = {},
    CursorlineSign = {},
    CursorLineNr = { fg = C.color4, bg = C.surface_bright, bold = true },
    QuickfixLine = { bg = C.color0 },
    Pmenu = { fg = C.color7, bg = C.surface_container_low },
    PmenuSbar = { fg = C.surface_bright, bg = C.surface_container_low },
    PmenuSel = { fg = C.color4, bg = C.surface_container, bold = true }, -- not following base16
    PmenuThumb = { fg = C.color8, bg = C.surface_container_high },
    Tabline = { fg = C.color16, bg = C.surface_container },
    Tablinefill = { fg = C.surface_container, bg = C.surface_container },
    TablineSel = { fg = C.color7, bg = C.surface, bold = true },

    -- neovim's regex syntax highlight
    Boolean = C.color3,
    Character = { fg = C.color1, bold = true },
    Comment = { fg = C.color16, italic = true },
    Condition = C.color5,
    Constant = C.color3,
    Define = C.color5,
    Delimiter = C.color7,
    Float = C.color3,
    ["Function"] = C.color4,
    Identifier = C.color1,
    Include = C.color4,
    Keyword = { fg = C.color5, italic = true },
    Label = C.color3,
    Number = C.color3,
    Operator = C.color7,
    Preproc = C.color3,
    ["Repeat"] = { fg = C.color3, italic = true },
    Special = C.color6,
    Specialchar = { link = "character" },
    Statement = C.color5,
    String = C.color2,
    Structure = { fg = C.color5, italic = true },
    Tag = C.color3,
    Todo = C.color4,
    Type = { fg = C.color3, bold = true },
    Typedef = { link = "type" },

    -- diff syntax highlighting
    DiffAdd = { fg = C.color2, bg = C.color0 },
    DiffChange = { fg = C.color6, bg = C.color0 },
    DiffDelete = { fg = C.color1, bg = C.color0 },
    DiffText = { fg = C.color4, bg = C.color0 },
    DiffAdded = C.color2,
    DiffFile = C.color1,
    DiffNewfile = C.color2,
    DiffLine = C.color4,
    DiffRemoved = C.color1,

    -- spell
    SpellBad = { underline = true, sp = C.color1 },
    SpellCap = { underline = true, sp = C.color4 },
    SpellRare = { underline = true, sp = C.color5 },
    SpellLocal = { underline = true, sp = C.color6 },

    -- lsp
    LspInlayHint = { bg = C.surface_container, fg = C.on_surface_low },
}
