local C = require "ui.theme.colors"
return {
    CmpCompletionNormal = { bg = "none" },
    CmpCompletionBorder = { fg = C.color17 },
    CmpDocumentationNormal = { bg = "none" },
    CmpDocumentationBorder = { fg = C.color17 },
    CmpItemSelected = { bg = C.surface_bright },
    -- Client item kinds, the following are builtin to cmpk.
    CmpItemAbbrDeprecated = { fg = C.color7, strikethrough = true },
    CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
    CmpItemAbbrMatch = { fg = C.color6, bold = true },
    CmpItemKindSnippet = { fg = C.color2 },
    CmpItemKindConstant = { fg = C.color3 },
    CmpItemKindConstructor = { fg = C.color4 },
    CmpitemKindEnum = { fg = C.color3 },
    CmpItemKindEvent = { fg = C.color1 },
    CmpitemKindInterface = { fg = C.color3 },
    CmpItemKindKeyboard = { fg = C.color5 },
    CmpItemKindClass = { fg = C.color3 },
    CmpItemKindModule = { fg = C.color1 },
    CmpItemKindOperator = C.on_surface_low,
    CmpitemKindTypeParameter = { fg = C.color3 },
    CmpItemKindUnit = { fg = C.color2 },
    CmpItemKindVariable = { fg = C.color6 },
    CmpItemKindInterface = { link = "CmpItemKindVariable" },
    CmpItemKindText = { link = "CmpItemKindVariable" },
    CmpItemKindFunction = { fg = C.color4 },
    CmpItemKindMethod = { link = "CmpItemKindFunction" },
    CmpItemKindProperty = { link = "CmpItemKindKeyword" },
    CmpItemKindFolder = { fg = "#f1d068" },
    CmpItemKindFile = { fg = C.color1 },
    CmpItemKindStruct = { fg = C.color3 },
    -- Cmp doc
    CmpDocNormalFloat = { bg = C.surface_container_highest },
    CmpDocFloatBorder = { bg = C.surface_container_highest, fg = C.on_surface_lower, blend = 10 },
}
