use serde::Serialize;

use crate::cached::Cacheable;

#[macro_use]
extern crate tracing;

mod cached;
mod github;
mod weather;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .compact()
        .without_time()
        // stdout is for messages to quickshell.
        .with_writer(std::io::stderr)
        .init();
    info!("Starting quickshell backend");

    let dir = {
        let base_dirs = xdg::BaseDirectories::new();
        let state_dir = base_dirs.get_state_home().unwrap();
        state_dir.join("qs-backend")
    };
    // needed otherwise there's no good.
    tokio::fs::create_dir_all(&dir)
        .await
        .expect("failed to create state dir");

    let path = dir.join("weather.json");
    tokio::spawn(async move {
        let mut weather = weather::Weather::default();
        if let Err(err) = weather.run(path).await {
            error!(?err, "Failed to run weather service")
        }
    });

    let path = dir.join("github-notifications.json");
    tokio::spawn(async move {
        let mut notifications = github::GitHubNotifications::new()
            .await
            .expect("failed to create github notifications service");
        if let Err(err) = notifications.run(path).await {
            error!(?err, "Failed to run github notifications service")
        }
    });

    tokio::signal::ctrl_c().await.unwrap()
}

/// An event generated by a task.
#[derive(Debug, Serialize, PartialEq)]
#[serde(tag = "kind", content = "data")]
pub enum Event {}
