[buildPlans.IosevkaFhtMono]
family = "Fht Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

  [buildPlans.IosevkaFhtMono.variants]
  inherits = "ss08"

    [buildPlans.IosevkaFhtMono.variants.design]
    capital-n = "standard-serifless"
    capital-w = "curly-serifless"
    capital-x = "straight-serifless"
    f = "serifless"
    g = "double-storey"
    l = "serifed"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    z = "straight-serifless"
    capital-delta = "straight"
    lower-delta = "rounded"
    zero = "slashed"
    four = "semi-open-serifless"
    five = "upright-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "penta-high"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    lig-ltgteq = "flat"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

[buildPlans.IosevkaFhtMono.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaFhtMono.widths.Normal]
shape = 600
menu = 5
css = "normal"
