# https://github.com/shytikov/pragmasevka
# Licensed under OFL1.1
[buildPlans.IosevkaPragmasevka]
family = "Pragmasevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

hintParams = ["-a", "qqq"]

    [buildPlans.IosevkaPragmasevka.widths.normal]
    shape = 500
    menu  = 5
    css   = "normal"

    [buildPlans.IosevkaPragmasevka.metricOverride]
    leading = 1100
    xHeight = 550

    [buildPlans.IosevkaPragmasevka.ligations]
    inherits="default-calt"
    enables = [
        "eqslasheq",
        "kern-dotty",
        "kern-bars",
        "llggeq",
         "--fast-chaining--"
    ]
    disables = ["slash-asterisk"]

    [buildPlans.IosevkaPragmasevka.variants]
    inherits = "ss08"

    [buildPlans.IosevkaPragmasevka.weights.regular]
    shape = 425
    menu = 400
    css = 400

    [buildPlans.IosevkaPragmasevka.weights.semibold]
    shape = 600
    menu = 600
    css = 600

    [buildPlans.IosevkaPragmasevka.weights.bold]
    shape = 800
    menu = 700
    css = 700

    [buildPlans.IosevkaPragmasevka.weights.black]
    shape = 900
    menu = 900
    css = 900

    [buildPlans.IosevkaPragmasevka.slopes]
    upright = "default.Upright"
    italic = "default.Italic"
